### ISSUE TITLE
Snippet CSS pour overlay OBS

### ISSUE THREAD

**Issue by Tangeek42** [JohnXLivingston/peertube-plugin-livechat#109]
Le design par défaut s'intègre, selon moi, assez mal dans un overlay typique. Soit le texte noir sur fond transparent est difficilement lisible à moins d'avoir un fond clair, soit le fond blanc explose les yeux. Je propose donc une petite refonte CSS intégrable dans OBS. Je me suis concentré sur un contraste plus doux (directement repris de la charte d'openstreamingplatform) et une disparition des messages après 10 secondes, histoire de pas charger l'écran. J'ai aussi masqué les notifications.

Ce n'est pas parfait (je suis pas devweb pour le coup ^^ ), pour être vraiment soigné il faudrait je pense adapter l'HTML généré, peut-être en se basant sur des options disponibles dans l'UI (typiquement, différencier les premiers messages des follow-up n'est pas très pertinent dans ce contexte IMHO). À voir si je suis minoritaire, auquel cas pour les trois gus comme moi, voici un peu de CSS qui sauve les meubles. :D 

Je joins un petit mp4 montrant ce code en action.
https://user-images.githubusercontent.com/11335279/200174526-c0f7cb8f-f530-4f38-877b-f93ec373e1b7.mp4

```css
/* Tentative d'imiter le style d'OSP, pas parfait */
.message { background-color: #4F4F4F; border-radius: 10px; box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
		animation: cssAnimation 10s forwards;
		-webkit-animation: cssAnimation 10s forwards; }
.chat-msg__text { color: #cccccc !important; }
.chat-msg--followup * { margin-left:-35px; }

.chat-msg__time { float: right; color: gray !important; }

.chat-info__message { display: none; }
.chat-content__notifications { display: none; }
/* .avatar { display: none; } */ /* (Selon vos préférences) */

@keyframes cssAnimation {
	0%   {opacity: 1;}
	90%  {opacity: 1;}
	100% {opacity: 0;}
}
@-webkit-keyframes cssAnimation {
	0%   {opacity: 1;}
	90%  {opacity: 1;}
	100% {opacity: 0;}
}
```

```css
/* Version un peu moins aggressive.
Conserve le style d'origine mais masque les notifications et fais disparaitre les messages après 10s: */
.message { animation: cssAnimation 10s forwards;
		-webkit-animation: cssAnimation 10s forwards; }

.chat-info__message { display: none; }
.chat-content__notifications { display: none; }

@keyframes cssAnimation {
	0%   {opacity: 1;}
	90%  {opacity: 1;}
	100% {opacity: 0;}
}
@-webkit-keyframes cssAnimation {
	0%   {opacity: 1;}
	90%  {opacity: 1;}
	100% {opacity: 0;}
}
```
